const amenitiesData = {
    "Infrastructure Amenities": [
      "Tar roads",
      "Street lighting",
      "Water supply",
      "Sewage treatment plant",
      "Rainwater harvesting system",
      "Power backup (generator)",
      "Underground electrical cabling",
      "Telecommunication connectivity",
    ],
    "Security and Safety Features": [
      "Gated community with 24/7 security",
      "CCTV surveillance (biometric, RFID, etc.)",
      "Access control systems",
      "Emergency response system",
      "Fire fighting systems",
      "Secure parking",
      "Perimeter fencing",
    ],
    "Recreational Amenities": [
      "Clubhouse",
      "Swimming pool",
      "Gymnasium",
      "Yoga and meditation hall",
      "Indoor games (table tennis, billiards, etc.)",
      "Outdoor games (tennis, basketball, etc.)",
      "Children's play area",
      "Park and green spaces",
      "Walking/jogging trails",
      "Amphitheater",
    ],
    "Convenience Amenities": [
      "Convenience store",
      "Supermarket",
      "Pharmacy",
      "Restaurant/Café",
      "ATM",
      "Laundry services",
      "Pet park",
      "Community hall",
    ],
    "Health and Wellness Amenities": [
      "Medical center",
      "Spa and wellness center",
      "Sauna and steam room",
      "Jacuzzi",
      "Salon and beauty parlor",
    ],
    "Luxury Amenities": [
      "Private cinema",
      "Virtual golf",
      "Squash court",
      "Badminton court",
      "Cricket pitch",
      "Football field",
      "Luxury lounge",
      "Business center",
    ],
    "Eco-Friendly Amenities": [
      "Solar power generation",
      "Organic waste management",
      "Recycling facilities",
      "Green roofs",
      "Rainwater harvesting system",
    ],
    "Landscape Features": [
      "Landscaped gardens",
      "Water features (ponds, fountains, etc.)",
      "Green spaces",
      "Tree-lined avenues",
      "Flowering plants and shrubs",
    ],
    "Technology Features": [
      "Wi-Fi connectivity",
      "Smart home automation",
      "Energy-efficient systems",
      "Solar power generation",
      "Fiber optic connectivity",
    ],
    "Other Amenities": [
      "Guest rooms",
      "Visitor parking",
      "Pet-friendly community",
      "Disabled-friendly infrastructure",
      "Waste management system",
    ],
    "Pet-Friendly Features": [
      "Pet park",
      "Pet-friendly community",
      "Pet grooming services",
    ],
    "Disabled-Friendly Features": [
      "Ramps and elevators",
      "Wheelchair-accessible pathways",
      "Disabled-friendly toilets",
    ],
  };
  
  export default amenitiesData;
  